tasks:
    - name: Install Asciidoctor
      init: |
          sudo apt-get update
          sudo apt-get install -y asciidoctor

    - name: Install npm dependencies
      init: npm install

vscode:
    extensions:
        - esbenp.prettier-vscode
