tasks:
    - name: Install Asciidoctor
      before: |
          gem install asciidoctor
          exit

    - name: Install npm dependencies
      init: npm install

    - name: Add .env file
      init: cp sample.env .env

vscode:
    extensions:
        - esbenp.prettier-vscode

ports:
    - port: 5000
      onOpen: open-browser
      visibility: public
