tasks:
    - name: Install Asciidoctor
      init: |
          echo "BEFORE"
          sudo apt-get install -y asciidoctor
          echo "AFTER"

    - name: Install npm dependencies
      init: npm install

vscode:
    extensions:
        - esbenp.prettier-vscode
