image: asciidoctor/docker-asciidoctor

tasks:
    - name: Install npm dependencies
      init: npm install

vscode:
    extensions:
        - esbenp.prettier-vscode

ports:
    - port: 5000
      onOpen: open-browser
      visibility: public
