name: Build and deploy web app
on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/build-deploy-web-app.yaml"
            - "public/**"
            - "summary/**"
            - "util/build.sh"
            - "index.js"
            - "package-lock.json"
            - "package.json"
    pull_request:
        branches:
            - main
        paths:
            - ".github/workflows/build-deploy-web-app.yaml"
            - "public/**"
            - "summary/**"
            - "util/build.sh"
            - "index.js"
            - "package-lock.json"
            - "package.json"
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        container: "docker://asciidoctor/docker-asciidoctor:latest"
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Only keep relevant files
              run: |
                  # Delete all old files
                  rm -rf ./*

                  # Get latest files
                  git restore -s main public summary util/build.sh index.js package-lock.json package.json

            - name: Build Asciidoctor site
              run: |
                  chmod +x util/build.sh
                  ./util/build.sh
                  rm -rf summary util/build.sh

            - name: Deploy to Deta
              uses: BogDAAAMN/deta-deploy-action@v1.0.1
              with:
                  deta-access-token: ${{ secrets.DETA_TOKEN }}
                  deta-name: catchup
                  deta-project: otc
                  deta-project-dir: "."
