name: Reminder Tweet

on:
    schedule:
        - cron: "30 11 * * 6" # Every Saturday at 11:30 AM UTC (i.e., 5 PM IST)
    workflow_dispatch:

jobs:
    send-reminder-tweet:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  persist-credentials: false

            - name: Set environment variables
              run: |
                  sudo apt-get update
                  sudo apt-get install nodejs

                  upcoming_catchup_number=$(node util/get-next-catchup-number.js)
                  echo "UPCOMING_CATCHUP_NUMBER=${upcoming_catchup_number}" >> ${GITHUB_ENV}

                  prev_catchup_number=$(node util/get-latest-catchup-number.js)
                  echo "PREV_CATCHUP_NUMBER=${prev_catchup_number}" >> ${GITHUB_ENV}

                  catchup_date=$(date +"%b %d")
                  echo "CATCHUP_DATE=${catchup_date}" >> ${GITHUB_ENV}

            - name: Send reminder Tweet
              uses: Eomm/why-don-t-you-tweet@v1
              with:
                  tweet-message: |
                      Reminder! 🚨

                      The ${{ env.UPCOMING_CATCHUP_NUMBER }} OTC CatchUp session will be held today (${{ env.CATCHUP_DATE }}) from 10:30 PM IST.

                      Join us for an informal open-to-all Tech discussion!

                      Previous session details 👇
                      https://catchup.ourtech.community/summary/${{ env.PREV_CATCHUP_NUMBER }}

                      #OTC #OTCCatchUp #Community #Tech
              env:
                  TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
                  TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
                  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
                  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
