name: Telegram Joining Message

on:
    schedule:
        - cron: "50 16 * * 6" # Every Saturday at 4:50 PM UTC (i.e., 10:20PM IST)
    workflow_dispatch:

jobs:
    send-msg:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  persist-credentials: false

            - name: Set environment variables
              run: |
                  sudo apt-get update
                  sudo apt-get install nodejs
                  catchup_number=$(node util/get-next-catchup-number.js)
                  echo "CATCHUP_NUMBER=${catchup_number}" >> ${GITHUB_ENV}

            - name: Send joining message on OTC's Telegram group
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_CHAT_ID }}
                  token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                  message: |
                      **${{ env.CATCHUP_NUMBER }} OTC CatchUp**

                      An informal open-to-all Tech discussion!

                      We start at 10:30 PM IST.

                      Join in at any time! 👇
                      https://catchup.ourtech.community/attend
