name: Telegram reminder message

on:
    schedule:
        - cron: "30 11 * * 6" # Every Saturday at 11:30 AM UTC (i.e., 5 PM IST)
    workflow_dispatch:

jobs:
    send-reminder-message:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  persist-credentials: false

            - name: Set environment variables
              run: |
                  sudo apt-get update
                  sudo apt-get install nodejs

                  upcoming_catchup_number=$(node util/get-next-catchup-number.js)
                  echo "UPCOMING_CATCHUP_NUMBER=${upcoming_catchup_number}" >> ${GITHUB_ENV}

                  prev_catchup_number=$(node util/get-latest-catchup-number.js)
                  echo "PREV_CATCHUP_NUMBER=${prev_catchup_number}" >> ${GITHUB_ENV}

                  catchup_date=$(date +"%b %d")
                  echo "CATCHUP_DATE=${catchup_date}" >> ${GITHUB_ENV}

            - name: Send reminder message on OTC's Telegram group
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_CHAT_ID }}
                  token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                  format: markdown
                  disable_web_page_preview: true
                  message: |
                      Reminder! 🚨

                      The ${{ env.UPCOMING_CATCHUP_NUMBER }} OTC CatchUp session will be held today (${{ env.CATCHUP_DATE }}) from 10:30 PM IST.

                      Join us for an informal open-to-all Tech discussion!

                      Joining link 👇
                      https://catchup.ourtech.community/attend

                      Previous session details 👇
                      https://catchup.ourtech.community/summary/${{ env.PREV_CATCHUP_NUMBER }}
